version: '3'
services:
  web:
    build: ./webpage/
    environment:
      - ENV=local
    ports:
      - "3001:3001"
    volumes:
      - ./webpage:/usr/src/web_app

  querier:
    build: ./querier/
    restart: always
    environment:
      - ENCODER_API_BASE_URL=http://encoder:8080
    ports:
      - "8080:8081"
    links:
      - encoder
      - mysql
    depends_on:
      - mysql
      - encoder

  encoder:
    build: ./sentence_encoder/
    ports:
      - "8080:8080"

  crawler:
    build: ./crawler/
    restart: always
    environment:
      - ENCODER_API_BASE_URL=http://encoder:8080
    links:
      - encoder
      - mysql
    depends_on:
      - mysql
      - encoder

  mysql:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=search_engine
    ports:
      - '3306:3306'
    expose:
      - '3306'
