openapi: 3.0.0
info:
  title: Sentence Encoder
  description: This is the sentence encoder interface.
  version: 0.0.0
servers:
- url: /
paths:
  /health:
    get:
      operationId: health
      x-openapi-router-controller: api.controllers.default_controller
      responses:
        '200':
          description: OK
  /encode:
    post:
      summary: Returns a list of vectors.
      description: This will encode your list of texts to a list of vectors.
      operationId: encode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfTexts'
        required: true
      responses:
        200:
          description: A JSON array text vectors.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/TextVector'
      x-openapi-router-controller: api.controllers.default_controller
components:
  schemas:
    TextVector:
      type: object
      properties:
        text:
          type: string
        vector:
          type: array
          items:
            type: number
            format: float
      example:
        vector:
        - 0.8008282
        - 0.8008282
        text: text
    ListOfTexts:
      type: array
      items:
        type: string

