openapi: 3.0.0
info:
  title: Querier
  description: This is querier interface.
  version: 0.0.1
servers:
- url: /
paths:
  /query:
    get:
      summary: Returns a page.
      operationId: query
      parameters:
        - in: query
          name: text
          required: true
          schema:
            type: string
      responses:
        200:
          description: A webpage.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfWebPages'
      x-openapi-router-controller: api.controllers.default_controller
components:
  schemas:
    ListOfWebPages:
      type: array
      items:
        $ref: '#/components/schemas/WebPage'
    WebPage:
      type: object
      properties:
        url:
          type: string
        title:
          type: string